### ISSUE TITLE
add custom Referer

### ISSUE THREAD

**Issue by Fsystem** [carina-studio/AutoUpdater#2]
I need to set the Referer in the header of a network request to download my program stored on OSS. Can I add a runtime parameter to pass in a custom  Referer?

**Comment by hamster620** [comment]
@Fsystem The core function of AutoUpdater is implemented in [CarinaStudio.AppBase.AutoUpdate](https://github.com/carina-studio/AppBase/tree/master/AutoUpdate) package which does not support setting referer. 

If you need setting referer maybe you can help to modify the [method](https://github.com/carina-studio/AppBase/blob/cf4508d1a10a21c1e92aac2bff18907fa2dbdd73/AutoUpdate/Updater.cs#L367) then we can have a release of AppBase, and integrate it into AutoUpdater.

**Comment by Fsystem** [comment]
@hamster620 I've initiated a pull request in AppBase. Could you please review and merge it, followed by releasing a new NuGet package? Afterwards, I will submit the modifications for the AutoUpdater.

**Comment by hamster620** [comment]
Supported in [2.1.0.1001](https://github.com/carina-studio/AutoUpdater/releases/tag/2.1.0.1001):
- use ```-package-manifest-http-referer``` argument followed by URI to specify HTTP referer for sending request of package manifest.
- use ```-package-http-referer``` argument followed by URI to specify HTTP referer for sending request of downloading package.
- use ```-bypass-cert-validation``` to bypass SSL certification validation.
- use ```-http-user-agent``` to specify HTTP user agent for all request.

**Comment by Fsystem** [comment]
@hamster620 
Thank you so much for resolving this issue. Keep up the good work!
